name: "web-storage-development"
services:

  # INTERN PORT: 3306
  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
      target: base
    container_name: mysql-nebalus-storage
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "main"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "123456"
    volumes:
      - /var/lib/mysql
    networks:
      - private-net

  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
      target: base
    container_name: redis-nebalus-storage
#    environment:
#      REDIS_PASSWORD: "12345"
#    command: [ "redis-server", "--requirepass", "$$REDIS_PASSWORD" ]
    command: [ "redis-server" ]
    networks:
      - private-net

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter-nebalus-storage
    environment:
      REDIS_ADDR: "redis:6379"
#      REDIS_PASSWORD: "123456"
    networks:
      - private-net

  elasticsearch:
    build:
      context: .
      dockerfile: docker/elasticsearch/Dockerfile
      target: base
    container_name: elasticsearch-nebalus-storage
    environment:
      - ELASTIC_PASSWORD=123456
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '9200:9200'
    networks:
      - public-net

  kibana:
    build:
      context: .
      dockerfile: docker/kibana/Dockerfile
      target: base
    container_name: kibana-nebalus-storage
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - '5601:5601'
    networks:
      - public-net
    depends_on:
      - elasticsearch

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-nebalus-storage
    ports:
      - '8080:80'
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - private-net
      - public-net

networks:
  public-net:
    name: public-net
  private-net:
    name: private-net
