global:
  scrape_interval: 15s  # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'  # Scrape Prometheus itself
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'redis_exporter'
    static_configs:
      - targets: ["redis-exporter:9121"]
